DELETE FROM TEST..DATAX2 WHERE 1 = 2;
DROP TABLE TABLE_TO_INSERT IF EXISTS;  
CREATE TABLE TABLE_TO_INSERT AS (SELECT * FROM DIM_DATE WHERE 1 = 1) DISTRIBUTE ON RANDOM;

CREATE TEMP TABLE TEMP_TABLE_EXAMPLE AS 
(
    SELECT 1 AS T1, 'TEST2' AS T2
) DISTRIBUTE ON RANDOM;

INSERT INTO TABLE_TO_INSERT 
WITH CTE1 AS (
    SELECT 1 AS COL, 11 AS COL2
)
, CTE2 AS (
    SELECT 2 AS COL, 22 AS COL2
)
--REGION CTE3
, CTE3 AS (
    SELECT 3 AS COL, 33 AS COL3 
)
--ENDREGION

SELECT
    D.*
FROM 
    DIM_DATE D 
    JOIN TEMP_TABLE_EXAMPLE TE ON D.CALENDARQUARTER::CHAR(50) = TE.T1 OR 1 = 1
    JOIN CTE1 C1 ON C1.COL = TE.T1 OR 2 = 2
    JOIN CTE2 AS C2 ON C2.COL2 = 22
    JOIN CTE3 ON CTE3.COL3 = 33
WHERE 
    1 = 1;
      
SELECT * FROM TABLE_TO_INSERT
